name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
    build-job:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - run: python3 -V
        - name: Build
          run: echo "Build ok"

    test-job:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Install dependencies
          run: pip install Flask
        - uses: AppThreat/sast-scan-action@master
          with:
            type: "python"

    deploy-job:
      runs-on: ubuntu-latest
      needs: test-job
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Log in to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_PASSWORD }}

        - name: Build Docker image
          run: docker build -t ggamorim/as02-devops-ggamorim:latest .

        - name: Push Docker image
          run: docker push ggamorim/as02-devops-ggamorim:latest

        - name: Send notification
          if: github.event_name == 'pull_request'
          env:
            DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          run: |
            curl -X POST -H 'Content-type: application/json' \
              --data '{"content": "Uma nova imagem Docker foi publicada!"}' \
              $DISCORD_WEBHOOK
       